/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.residenciasunal.residenciasunal;

import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class PanelEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstudiante
     */
    public PanelEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cedula = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        Puntaje = new javax.swing.JLabel();
        Asignado = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 40));
        setMinimumSize(new java.awt.Dimension(400, 40));
        setPreferredSize(new java.awt.Dimension(400, 40));

        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cédula");
        add(Cedula);

        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");
        add(Nombre);

        Carrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carrera.setText("Carrera");
        add(Carrera);

        Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntaje.setText("Puntaje");
        add(Puntaje);

        Asignado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asignado.setText("asignado");
        add(Asignado);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAsignado() {
        return Asignado;
    }

    public JLabel getCarrera() {
        return Carrera;
    }

    public JLabel getCedula() {
        return Cedula;
    }

    public JLabel getNombre() {
        return Nombre;
    }

    public JLabel getPuntaje() {
        return Puntaje;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Asignado;
    public javax.swing.JLabel Carrera;
    public javax.swing.JLabel Cedula;
    public javax.swing.JLabel Nombre;
    public javax.swing.JLabel Puntaje;
    // End of variables declaration//GEN-END:variables
}
