/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.residenciasunal.residenciasunal;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    HashMap mapEstudiantes;
    MinHeap heapEstudiantes;

    public View() {
        initComponents();
        mapEstudiantes = new HashMap();
        heapEstudiantes = new MinHeap();
    }
    
    private boolean validarCampos(String cedulaStr, String nombre, String carrera, String puntajeStr) {
        if (cedulaStr.isEmpty() || nombre.isEmpty() || carrera.isEmpty() || puntajeStr.isEmpty()) {
            String msg = "Todos los campos son obligatorios.";
            System.err.println(msg);
            JOptionPane.showMessageDialog(this, msg, "Error de validacion", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * Intenta parsear una cédula a entero, muestra mensaje si falla
     * @return valor entero de la cédula, o -1 si falla
     */
    private int parsearCedula(String cedulaStr) {
        try {
            return Integer.parseInt(cedulaStr);
        } catch (NumberFormatException ex) {
            String msg = "La cedula debe ser un numero entero.";
            System.err.println(msg + " Valor recibido: " + cedulaStr);
            JOptionPane.showMessageDialog(this, msg, "Error de formato", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }

    /**
     * Intenta parsear un puntaje a long, muestra mensaje si falla
     * @return valor long del puntaje, o -1 si falla
     */
    private long parsearPuntaje(String puntajeStr) {
        try {
            return Long.parseLong(puntajeStr);
        } catch (NumberFormatException ex) {
            String msg = "El puntaje debe ser un número entero.";
            System.err.println(msg + " Valor recibido: " + puntajeStr);
            JOptionPane.showMessageDialog(this, msg, "Error de formato", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBusqueda = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TituloBuscar = new javax.swing.JLabel();
        TextoBusqueda = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PanelPrioridad = new javax.swing.JPanel();
        TituloPrioridad = new javax.swing.JLabel();
        PanelInformacion = new javax.swing.JPanel();
        TituloInformacion = new javax.swing.JLabel();
        TextoCedula = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoCarrera = new javax.swing.JTextField();
        TextoPuntaje = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));

        PanelBusqueda.setBackground(java.awt.Color.white);
        PanelBusqueda.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        PanelBusqueda.setLayout(new javax.swing.BoxLayout(PanelBusqueda, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setMaximumSize(new java.awt.Dimension(500, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 200));
        jPanel5.setPreferredSize(new java.awt.Dimension(343, 70));

        TituloBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloBuscar.setText("Buscar por cédula:");
        jPanel5.add(TituloBuscar);

        TextoBusqueda.setMaximumSize(new java.awt.Dimension(70, 26));
        TextoBusqueda.setMinimumSize(new java.awt.Dimension(70, 26));
        TextoBusqueda.setPreferredSize(new java.awt.Dimension(130, 26));
        TextoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoBusquedaActionPerformed(evt);
            }
        });
        jPanel5.add(TextoBusqueda);

        jButton3.setBackground(java.awt.Color.lightGray);
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Asignar");
        jPanel5.add(jButton3);

        BotonEliminar.setBackground(java.awt.Color.red);
        BotonEliminar.setForeground(java.awt.Color.white);
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(BotonEliminar);

        PanelBusqueda.add(jPanel5);
        PanelBusqueda.add(jPanel6);

        getContentPane().add(PanelBusqueda, java.awt.BorderLayout.CENTER);

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("RESIDENCIAS UNAL");
        getContentPane().add(Titulo, java.awt.BorderLayout.PAGE_START);

        PanelPrioridad.setBackground(java.awt.Color.white);
        PanelPrioridad.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        PanelPrioridad.setLayout(new javax.swing.BoxLayout(PanelPrioridad, javax.swing.BoxLayout.Y_AXIS));

        TituloPrioridad.setText("Lista de prioridad");
        PanelPrioridad.add(TituloPrioridad);

        getContentPane().add(PanelPrioridad, java.awt.BorderLayout.EAST);

        PanelInformacion.setBackground(java.awt.Color.white);
        PanelInformacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        PanelInformacion.setLayout(new javax.swing.BoxLayout(PanelInformacion, javax.swing.BoxLayout.Y_AXIS));

        TituloInformacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloInformacion.setText("Student Info");
        TituloInformacion.setMaximumSize(new java.awt.Dimension(90, 15));
        TituloInformacion.setMinimumSize(new java.awt.Dimension(90, 15));
        TituloInformacion.setPreferredSize(new java.awt.Dimension(90, 15));
        PanelInformacion.add(TituloInformacion);

        TextoCedula.setText("Cedula");
        TextoCedula.setMaximumSize(new java.awt.Dimension(90, 30));
        TextoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCedulaActionPerformed(evt);
            }
        });
        PanelInformacion.add(TextoCedula);

        TextoNombre.setText("Nombre");
        TextoNombre.setMaximumSize(new java.awt.Dimension(90, 30));
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });
        PanelInformacion.add(TextoNombre);

        TextoCarrera.setText("Carrera");
        TextoCarrera.setMaximumSize(new java.awt.Dimension(90, 30));
        TextoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCarreraActionPerformed(evt);
            }
        });
        PanelInformacion.add(TextoCarrera);

        TextoPuntaje.setText("Puntaje");
        TextoPuntaje.setMaximumSize(new java.awt.Dimension(90, 30));
        TextoPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoPuntajeActionPerformed(evt);
            }
        });
        PanelInformacion.add(TextoPuntaje);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setMaximumSize(new java.awt.Dimension(500, 100));

        BotonAgregar.setBackground(java.awt.Color.blue);
        BotonAgregar.setForeground(java.awt.Color.white);
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(BotonAgregar);

        PanelInformacion.add(jPanel4);

        getContentPane().add(PanelInformacion, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCarreraActionPerformed

    private void TextoPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoPuntajeActionPerformed

    private void TextoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoBusquedaActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        String cedulaStr = TextoCedula.getText().trim();
        String nombre = TextoNombre.getText().trim();
        String carrera = TextoCarrera.getText().trim();
        String puntajeStr = TextoPuntaje.getText().trim();

        // Validación centralizada
        if (!validarCampos(cedulaStr, nombre, carrera, puntajeStr)) {
            return;
        }

        int cedula = parsearCedula(cedulaStr);
        if (cedula < 0) {
            return;
        }

        long puntaje = parsearPuntaje(puntajeStr);
        if (puntaje < 0) {
            return;
        }

        if (!mapEstudiantes.containsKey(cedulaStr)) {
            Estudiante est = new Estudiante(cedula, nombre, carrera, puntaje);
            mapEstudiantes.put(cedulaStr, est);
            heapEstudiantes.insert(est);

            System.out.println("Estudiante agregado: " + est);
            JOptionPane.showMessageDialog(this, "Estudiante agregado correctamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            TextoCedula.setText("");
            TextoNombre.setText("");
            TextoCarrera.setText("");
            TextoPuntaje.setText("");
        } else {
            String msg = "La cedula “" + cedulaStr + "” ya está registrada.";
            System.err.println(msg);
            JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void TextoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCedulaActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        String cedulaStr = TextoBusqueda.getText().trim();

        if (cedulaStr.isEmpty()) {
            String msg = "Debe ingresar la cedula del estudiante a eliminar.";
            System.err.println(msg);
            JOptionPane.showMessageDialog(this, msg, "Error de validacion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (mapEstudiantes.containsKey(cedulaStr)) {
            Estudiante eliminado = mapEstudiantes.remove(cedulaStr);
            // heapEstudiantes.remove(eliminado);

            System.out.println("Estudiante eliminado: " + eliminado);
            JOptionPane.showMessageDialog(this, "Estudiante eliminado con exito.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            TextoCedula.setText("");
        } else {
            String msg = "No se encontro ningun estudiante con cedula “" + cedulaStr + "”.";
            System.err.println(msg);
            JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel PanelPrioridad;
    public javax.swing.JTextField TextoBusqueda;
    public javax.swing.JTextField TextoCarrera;
    public javax.swing.JTextField TextoCedula;
    public javax.swing.JTextField TextoNombre;
    public javax.swing.JTextField TextoPuntaje;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloBuscar;
    private javax.swing.JLabel TituloInformacion;
    private javax.swing.JLabel TituloPrioridad;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
